---
title: "데이터시각화 기말프로젝트"
author: "데이터테크전공 20173204 곽명빈"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)  
library(gridExtra)
```

```{r}
baby <- read.csv("출산율.csv")
lost <- read.csv("실업률.csv")
job <- read.csv("고용률.csv")
man <- read.csv("인구수.csv")
cost <- read.csv("사교육비.csv")

str(baby)
str(lost)
str(job)
str(man)
str(cost) 

mean1 <- cbind(baby$Mean, lost$Mean, job$Mean)

colnames(mean1) <- c("baby1", "lost1", "job1")
mean1 <- data.frame(mean1)


```

```{r}
co <- ggplot(data = man,
             aes(x = year, y = child))+
    geom_line(color = "#00AFBB", size = 1, group = 1)+
    geom_line(aes(x= year , y = oldman), color="red")+
    ggtitle("인구수") + 
    theme(plot.title = element_text(family = "serif", face = "bold", hjust = 0.5, size = 20, color = "darkblue"))


co
## child = 0~4세 oldman 70~74세


```


```{r}
a <- ggplot(data = baby,
       aes(x=Year, y=Mean))+
  geom_line(color = "#00AFBB", size = 1, group = 1)+
  ggtitle("출산률") + 
  theme(plot.title = element_text(family = "serif", face = "bold", hjust = 0.5, size = 20, color = "darkblue"))

b <- ggplot(data = lost,
       aes(x=Year, y=Mean))+
  geom_line(color = "#00AFBB", size = 1, group = 1)+
  ggtitle("실업률") + 
  theme(plot.title = element_text(family = "serif", face = "bold", hjust = 0.5, size = 20, color = "darkblue"))

c <- ggplot(data = job,
       aes(x=Year, y=Mean))+
  geom_line(color = "#00AFBB", size = 1, group = 1)+
  ggtitle("고용률") + 
  theme(plot.title = element_text(family = "serif", face = "bold", hjust = 0.5, size = 20, color = "darkblue"))


grid.arrange(a,b,c, ncol = 2, nrow = 2)
## 꺾은선 그래프를 통해 출산률과 실업률, 고용률을 표현 
```

```{r}
cor(mean1$baby1, mean1$lost1)
cor(mean1$baby1, mean1$job1)
cor(mean1$lost1, mean1$job1)
```

```{r}
d <- ggplot(data = mean1,
       aes(x = baby1, y = lost1))+
  geom_point(size = 2, color = "skyblue")+
  ggtitle("Scatter plot : 출산률과 실업률")+
  stat_smooth(method = 'lm', se=F)+
  theme(plot.title = element_text(size = 15))

e <- ggplot(data = mean1,
       aes(x = baby1, y = job1))+
  geom_point(size = 2, color = "skyblue")+
  ggtitle("Scatter plot : 출산률과 고용률")+
  stat_smooth(method = 'lm', se=F)+
  theme(plot.title = element_text(size = 15))

f <- ggplot(data = mean1,
       aes(x = lost1, y = job1))+
  geom_point(size = 2, color = "skyblue")+
  ggtitle("Scatter plot : 실업률과 고용률")+
  stat_smooth(method = 'lm', se=F)+
  theme(plot.title = element_text(size = 15))

  
grid.arrange(d,e,f, ncol = 2, nrow = 2)
```

